name: Masscan ipverse ASN

on:
  workflow_dispatch:
    inputs:
      asn:
        description: 'Nomor ASN (bisa banyak, pisah koma/spasi. Contoh: 13335, 209242)'
        required: true
        type: string

jobs:
  scan:
    strategy:
      matrix:
        port: [80, 8080, 8880, 2052, 2082, 2086, 2095, 443, 2053, 2083, 2087, 2096, 8443]

    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v5

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y masscan jq

      - name: Download IP list
        env:
          ASN_INPUT: ${{ inputs.asn }}
        run: |
          > iplist.txt
          for ASN in $(echo "$ASN_INPUT" | tr ',' ' '); do
            echo "Mengambil prefix AS${ASN}..."
            curl -fsSL "https://raw.githubusercontent.com/ipverse/as-ip-blocks/refs/heads/master/as/${ASN}/aggregated.json" \
              | jq -r '.prefixes.ipv4[]?' >> iplist.txt || echo "AS${ASN} gagal diunduh"
          done

          sed -i '/^$/d' iplist.txt
          sort -u iplist.txt -o iplist.txt
          echo "Total prefix: $(wc -l < iplist.txt)"

      - name: Scan
        run: |
          sudo masscan \
            -p${{ matrix.port }} \
            -iL iplist.txt \
            --excludefile exclude.txt \
            --rate 20000 \
            --retries 2 \
            --wait 5 \
            2>/dev/null \
            | bun check.js

      - name: Upload prxip.json
        if: always()
        uses: actions/upload-artifact@v7
        with:
          path: prxip.json
          archive: false
          if-no-files-found: ignore
          retention-days: 7
